service: salon-hub

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  stage: production
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    NODE_ENV: production

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
